# Generated by Django 5.1.4 on 2025-03-19 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_ad_category_alter_ad_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='api.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ad',
            name='subcategory',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='api.subcategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resume',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='api.category'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='api.subcategory'),
        ),
    ]
