# Generated by Django 5.1.4 on 2025-04-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='resume_documents/'),
        ),
        migrations.DeleteModel(
            name='ResumeDocument',
        ),
    ]
